Feature/g7 c1 35/update account attributes
nskrjabins/uob-se2-cgp-new-bank-cli pull request #10
Opened 2021-03-31 00:14 UTC by DevelopwithTom

## What?

Implimented an account number, sort code and account opening date.

## Why?

Customers will need the account number and sort code in order to recieve and make payments. The opening date of the account will help with calculating interest payments in future.

## How?

The account number and sort code is generated at random (but has to be 6 and 7 digits respectfully). The opening date uses the built in Calendar class to generate todays time and date.

## Testing?

None needed.

## Anything Else?

This the account number and sort code is being generated by random are temporary solutions to the problem. A persistent storage/ database is needed in order to impliment these features properly.

2021-04-01 10:39 UTC, AishhD reviewed
Hey @DevelopwithTom,

Code wise this looks good. 
I am bit confused by the file structure for instance we have this file path: `newbank/server/Account.java` and then we have `server/src/main/java/newbank/server/Account.java`.

I think theses file should all be in the same place, @de-mendes can you confirm the appropriate action?

2021-04-01 10:59 UTC, de-mendes requested changes
It looks good overall, just a couple of small changes and a couple of observations. Awesome job Tom

2021-04-01 10:59 UTC, de-mendes commented on newbank/server/Account.java
> +package newbank.server;
Tom I see this file is duplicated. The Account class exists now under the `newbank.server` package. This can be removed.

2021-04-01 10:59 UTC, de-mendes commented on server/src/main/java/newbank/server/Account.java
> +  public int sortCodeGenerator() {
This function looks good for this use case, however it is not deterministic and it can yield repeated outputs for different inputs.
For our use case is more than enough, but just an extra bit of info 🙂 .

2021-04-01 10:59 UTC, de-mendes commented on server/src/main/java/newbank/server/Account.java
> +  public Date todaysDate() {
If we're not testing these functions or reusing them somewhere else the scope could be private.

2021-04-03 15:15 UTC, DevelopwithTom commented on server/src/main/java/newbank/server/Account.java
> +  public int sortCodeGenerator() {
@de-mendes Yes, agreed. Not ideal but can be built upon with future introductions of persistent storage (or a Hashmap perhaps)

2021-04-03 15:17 UTC, DevelopwithTom commented on server/src/main/java/newbank/server/Account.java
> +  public Date todaysDate() {
@de-mendes Good point. I don't think these functions will benefit from testing at this stage.

2021-04-04 19:09 UTC, AishhD approved these changes
This looks great Tom!

2021-04-05 15:42 UTC, de-mendes commented
@DevelopwithTom I don't know of the file `newbank/server/Account.java` has been removed. It still appears on the changed files list. That files is not longer needed as it now is in the `server/src/main/java/newbank/server/Account.java`. Can you remove it?

2021-04-08 09:33 UTC, de-mendes approved these changes

2021-04-08 09:34 UTC, de-mendes commented
I am approving since that file will not cause any issue that I know of initially. But we could monitor the app after this PR has been merged to see if it breaks. 🚀

2021-04-11 18:30 UTC, merged

2021-04-11 18:48 UTC, DevelopwithTom commented
I couldn't figure out why that file was showing up as removed as it is present on my local version from which I made the PR request. I'll go ahead and merge and like you say, monitior the situation.