Added options list at initial login and HELP function for user
nskrjabins/uob-se2-cgp-new-bank-cli pull request #7
Opened 2021-03-20 00:38 UTC by ArifDarr

# [G7C1-XXX](https://bath-group7.atlassian.net/browse/G7C1-XXX)

N.B. The title of PR must also reference a [JIRA ticket number] in square brackets.

Optionally, you may even name the PR the same as the JIRA ticket, for example:

**[G7C1-32] Set up a PR template.**

## Description

Description of the change and why it was made.

## Definition of Done

This PR:

- [x] Delivers the functionality of the ticket it closes.
- [x] Is tested locally and includes unit tests using the [JUnit 5](https://junit.org/junit5/) (where applicable).
- [x] Follows [Java style guide](https://google.github.io/styleguide/javaguide.html).
- [x] Code is commented using the [Javadoc tool](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html) and any other applicable documentation e.g. on Confluence is updated.
- [x] Is rebased/cleaned up to be easy to review.

2021-03-20 16:55 UTC, AishhD requested changes
@ArifDarr Generally this looks really good!

I did notice that you haven't added any javadoc comments, can you please add these above any functions or classes you create? On my IntelliJ the short cut for this is `/**' followed by pressing enter, this may work for you too. You can find more info on javadoc here: https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html

I noticed you haven't updated your pull request description, please can you fill in the necessary details from the template.

I would be curious to hear about your thinking on adding the Help class. I personally would have added `printHelp` into a function on `NewBankClientHandler` as I don't think we need a class for one function. This is not a blocker, I'm just curious to hear more about your thinking.

2021-03-20 18:42 UTC, de-mendes commented
Hi @AriffDarr,

That string literal for the help message looks awesome. However, I believe string literals should be `static final` fields (constants) of our controller class (`NewBank`) then we can easilly return them with a helper function.

If the class is only going to have a string literal I believe it is too much encapsulation. I agree with @AishhD here, a `printHelp` method would sufice in this case.

Awesome work though.

2021-03-21 23:56 UTC, ArifDarr commented
Hi Guys,

As per comments following changes have been made:

* Added in javadoc comments.
* Descriptions updated.
* Help class removed and printHelp added into NewBankClientHandler.

Please go ahead and review, any issues please let me know and I'll be happy to adjust.

Thanks,

Arif.

2021-03-23 14:22 UTC, AishhD commented on newbank/server/NewBankClientHandler.java
> +  public static String printHelp(){
Hey @ArifDarr, this can be a  private method instead of public, as it is only be using inside this class. Public is used when you expect it to be accessed outside the class it is declared in

2021-03-23 14:25 UTC, AishhD commented
Great work @ArifDarr ! There is just one small change you could make. 

Also, you can remove this `N.B. The title of PR must also reference a [JIRA ticket number] in square brackets.` from the PR description

2021-03-23 15:07 UTC, ArifDarr commented on newbank/server/NewBankClientHandler.java
> +  public static String printHelp(){
Heya Aisha, Actually the class is accessed by both 'NewBankClientHandler' and 'NewBank', 'NewBank' uses the method for the 'HELP' function, hence the requirement for public.

Just to be sure I ran a quick check and it does indeed fail if you change the method to private.

2021-03-23 15:58 UTC, AishhD commented on newbank/server/NewBankClientHandler.java
> +  public static String printHelp(){
Ah yes! I missunderstood the flow, you are of course right

2021-03-23 15:58 UTC, AishhD approved these changes
Great work!

2021-03-23 19:15 UTC, merged